music/urls.py
from django.conf.urls import url
from . import views

app_name='music'

urlpatterns = [
    #/music/
    #url(r'^$', views.index, name='index'),
    # for generic view.
    url(r'^$', views.IndexView.as_view(), name='index'),

    #music/33/
   # url(r'^(?P<album_id>[0-9]+)/$', views.details, name='detail'),
    #for generic view
    url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='detail'),
    #music/33/favorite/
    #url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'album/add/$',views.addAlbum.as_view(),name='album-add')

]

website_first/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    #url(r'^$', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    #url(r'^videos/$', include('music.urls')),
]

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=200)
    album_logo = models.CharField(max_length=500)

    def get_absolute_url(self):
        return reverse('music:details',kwargs={'pk':self.pk})

    def __str__(self):
        return self.artist + "  :  " +self.album_title+" ; "


class Songs(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=300)
    ## boolean variable is used to mark if we select a particular song is our fav.
    is_favourate = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

music/views.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals


## render is a class which internally calls template loader , its a smart way to reduce the code.
#context is a predefined template which used to hold all required parametters for html template.
#from django.http import Http404
#from django.http import HttpResponse
# from models import Album, Songs
# from django.shortcuts import render,get_object_or_404

#required import for generic views
from models import Album, Songs
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView

## classes code for generic views

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'album_all'



    def get_queryset(self):
        return Album.objects.all()

class DetailsView(generic.DetailView):
    model=Album
    template_name = 'music/details.html'

class addAlbum(CreateView):
    model=Album
    fields = ['artist','album_title','album_logo']

class updateAlbum(UpdateView):
    model = Album

# desgin before implimenting generic design view.
#def index(request):
#    album_all=Album.objects.all()
#     context = {'album_all': album_all}
#     return render(request,'music/index.html',context)
#
#
# def details(request, album_id):
#     # try:
#     #     single_album=Album.objects.get(id=album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404("Id is invalid")
#     # get_object_or_404 is same as above try catch logic
#     single_album=get_object_or_404(Album,pk=album_id)
#     return render(request,'music/details.html',{'album':single_album})
#
# def favorite(request, album_id):
#     single_album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song= single_album.songs_set.get(pk=request.POST['song'])
#     except(KeyError,Songs.DoesNotSelected):
#         return render(request,'music/details.html',{'album':single_album,
#                                                      'error_message': "selected songs does not exists",
#                                                   })
#     else:
#         selected_song.is_favourate = True
#         selected_song.save()
#         return render(request, 'music/details.html', {'album': single_album})

music/templates/music/album_form.html
{% extends 'music/nav-base.html'%}
{% block title %}Add a new album{%endblock%}
{%block album_active%}active{% endblock %}

{%block viewcode %}

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal", action="",
                          method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                         {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>

                        </div>

                    </form>


                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

music/templates/music/details.html
{% extends 'music/nav-base.html'%}
{% block title %}Album-detail{%endblock%}

{% block viewcode %}

{%if error_message %}
<p>error message</p>
{%endif%}

{% if album.songs_set.count >= 1%}

<h2>{{album.artist}}</h2>


<table  align="left" >
        <tr align="left" bgcolor="grey">
            <th>song lyrix</th> <th>album_title</th>  <th>FileType</th> <th> Favorite </th>
        </tr>

        {% for song in album.songs_set.all %}
        <tr align="left">
            <td><input type="radio" id="radio{{ forloop.counter }}"
                       name="song" value="{{ song.id }}" >
                <label for="radio{{ forloop.counter }}"> {{song.song_title}}
                </label>
            </td>
            <td>{{album.album_title}}</td> <td>{{song.file_type}}</td>

             <!--{%if song.is_favourate%}-->
            <!--<td>Yes</td>-->
            <!--{% endif %}-->
        </tr>

            {%endfor%}
        <!--<tr>-->
            <!--<td align="center"><input type="submit" name="fav" value="favorite"></td>-->
            <!--<td></td>-->
        <!--</tr>-->

</table>
<!--</form>-->
{%else %}
    <h3> oops. no music added here, click
        <a href="/music/">here</a> to go back</h3>
{%endif%}
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">

<label class="control-label col-sm-2">{{ field.label_tag }}</label>
<div class="col-sm-10">{{field}}</div>
</div>
{%endfor%}

music/templates/music/index.html
{% extends 'music/nav-base.html'%}

{% block viewcode %}
<h2>Collect your collection's</h2>
<ul>
    {% for album in album_all %}
    <li>
        <!--<a href="/music/{{ album.id }}/">{{album.album_title}} </a>-->
    <a href ="{% url 'music:detail' album.id%}"> {{album.album_title}} </a>
    </li>
   {% endfor %}
</ul>
{% endblock %}

music/templates/music/nav-base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}KS-DJ{%endblock%}</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah|Indie+Flower" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{%  static 'music/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!--  header part -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
                    data-toggle="collapse" data-target="#topnavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'music:index' %}">KS-DJ</a>
        </div>
        <!-- items -->
        <div class="collapse navbar-collapse" id="topnavbar">
            <ul class="nav navbar-nav">
                <li class="{%block album_active%}active{% endblock %}">
                    <a href=" {% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" area-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-music" area-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>


                <form class="navbar-form navbar-left" role="search" method="get" action="">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default"> Search </button>

                </form>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" area-hidden="true"></span>&nbsp;
                        Add Album
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-off" area-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block viewcode %}

{% endblock %}
</body>
</html>